services:
  php:
    container_name: php8
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./backend:/var/www/html
    networks:
      - meta_network
    depends_on:
      - mysql
  mysql:
    image: mysql:8.1.0
    container_name: mysql
    #command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    ports:
      - "3307:3307"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - meta_network
  mariadb:
    image: docker.io/bitnami/mariadb:11.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      #- MARIADB_USER_PASSWORD=secret
      #- MARIADB_PASSWORD=secret
      #- MARIADB_ROOT_PASSWORD=secret
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - ./mariadb_data:/bitnami/mariadb
    networks:
      - meta_network
  moodle:
    image: docker.io/bitnami/moodle:4.5
    ports:
      - '8083:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      #- MOODEL_DATABASE_PASSWORD=secret
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=true
    volumes:
      - "./moodle/moodle_data:/bitnami/moodle"
      - "./moodle/moodledata_data:/bitnami/moodledata"
    depends_on:
      - mariadb
    networks:
      - meta_network
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - meta_network
    volumes:
      - ./backend/:/var/www/html/
      - ./logs/nginx:/var/log/nginx
    container_name: nginx

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3307
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - meta_network
networks:
  meta_network: